ALTER TABLE notification_mutes ADD COLUMN IF NOT EXISTS notify_room_join BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE notification_mutes ADD COLUMN IF NOT EXISTS notify_dm BOOLEAN NOT NULL DEFAULT FALSE;
