// ─── Vextorn Content Moderation Word List ──────────────────────────────────────
// Edit this file to add / remove terms without touching any logic.
// All terms are lowercase. The filter normalises input before matching.
//
// WORD_TERMS  → checked with word boundaries (\b…\b)
//               Safe for short words — won't fire inside legitimate words.
// PHRASE_TERMS → multi-word / substring expressions checked after normalisation.
//
// Categories:
//   profanity       — general swear words
//   sexual_content  — explicit sexual language, solicitation, harassment
//   slur            — ethnic, racial, gender, disability slurs
//   hate_speech     — threats, self-harm promotion, targeted abuse

export type FilterCategory = "profanity" | "sexual_content" | "slur" | "hate_speech";

export interface BannedEntry {
  term: string;
  category: FilterCategory;
}

// ── Single words (word-boundary matched) ──────────────────────────────────────
export const WORD_TERMS: BannedEntry[] = [

  // ── Core profanity ────────────────────────────────────────────────────────
  { term: "fuck",           category: "profanity" },
  { term: "fucker",         category: "profanity" },
  { term: "fucking",        category: "profanity" },
  { term: "fucks",          category: "profanity" },
  { term: "fucked",         category: "profanity" },
  { term: "motherfucker",   category: "profanity" },
  { term: "mf",             category: "profanity" },
  { term: "fuk",            category: "profanity" },
  { term: "phuck",          category: "profanity" },
  { term: "fck",            category: "profanity" },
  { term: "sht",            category: "profanity" },
  { term: "shit",           category: "profanity" },
  { term: "shitting",       category: "profanity" },
  { term: "shitty",         category: "profanity" },
  { term: "shithead",       category: "profanity" },
  { term: "bullshit",       category: "profanity" },
  { term: "horseshit",      category: "profanity" },
  { term: "bitch",          category: "profanity" },
  { term: "bitching",       category: "profanity" },
  { term: "bitchy",         category: "profanity" },
  { term: "btch",           category: "profanity" },
  { term: "bastard",        category: "profanity" },
  { term: "asshole",        category: "profanity" },
  { term: "assholes",       category: "profanity" },
  { term: "arsehole",       category: "profanity" },
  { term: "douchebag",      category: "profanity" },
  { term: "douche",         category: "profanity" },
  { term: "prick",          category: "profanity" },
  { term: "jackass",        category: "profanity" },
  { term: "wanker",         category: "profanity" },
  { term: "tosser",         category: "profanity" },
  { term: "bollocks",       category: "profanity" },
  { term: "bellend",        category: "profanity" },
  { term: "crap",           category: "profanity" },
  { term: "jerk",           category: "profanity" },
  { term: "moron",          category: "profanity" },
  { term: "idiot",          category: "profanity" },
  { term: "imbecile",       category: "profanity" },
  { term: "scumbag",        category: "profanity" },
  { term: "scum",           category: "profanity" },

  // ── Sexual harassment / explicit ──────────────────────────────────────────
  { term: "cock",           category: "sexual_content" },
  { term: "cocks",          category: "sexual_content" },
  { term: "cocksuck",       category: "sexual_content" },
  { term: "cocksucker",     category: "sexual_content" },
  { term: "dick",           category: "sexual_content" },
  { term: "dicks",          category: "sexual_content" },
  { term: "dickhead",       category: "sexual_content" },
  { term: "pussy",          category: "sexual_content" },
  { term: "cunt",           category: "sexual_content" },
  { term: "twat",           category: "sexual_content" },
  { term: "tits",           category: "sexual_content" },
  { term: "titties",        category: "sexual_content" },
  { term: "boobs",          category: "sexual_content" },
  { term: "boob",           category: "sexual_content" },
  { term: "booty",          category: "sexual_content" },
  { term: "blowjob",        category: "sexual_content" },
  { term: "handjob",        category: "sexual_content" },
  { term: "bj",             category: "sexual_content" },
  { term: "masturbate",     category: "sexual_content" },
  { term: "masturbation",   category: "sexual_content" },
  { term: "masturbating",   category: "sexual_content" },
  { term: "fap",            category: "sexual_content" },
  { term: "orgasm",         category: "sexual_content" },
  { term: "ejaculate",      category: "sexual_content" },
  { term: "ejaculation",    category: "sexual_content" },
  { term: "jizz",           category: "sexual_content" },
  { term: "cum",            category: "sexual_content" },
  { term: "cumshot",        category: "sexual_content" },
  { term: "dildo",          category: "sexual_content" },
  { term: "vibrator",       category: "sexual_content" },
  { term: "porn",           category: "sexual_content" },
  { term: "porno",          category: "sexual_content" },
  { term: "pornography",    category: "sexual_content" },
  { term: "xxx",            category: "sexual_content" },
  { term: "onlyfans",       category: "sexual_content" },
  { term: "camgirl",        category: "sexual_content" },
  { term: "camboy",         category: "sexual_content" },
  { term: "prostitute",     category: "sexual_content" },
  { term: "prostitution",   category: "sexual_content" },
  { term: "whore",          category: "sexual_content" },
  { term: "slut",           category: "sexual_content" },
  { term: "hooker",         category: "sexual_content" },
  { term: "skank",          category: "sexual_content" },
  { term: "anal",           category: "sexual_content" },
  { term: "anus",           category: "sexual_content" },
  { term: "rape",           category: "sexual_content" },
  { term: "rapist",         category: "sexual_content" },
  { term: "raping",         category: "sexual_content" },
  { term: "molest",         category: "sexual_content" },
  { term: "molestation",    category: "sexual_content" },
  { term: "grope",          category: "sexual_content" },
  { term: "fondling",       category: "sexual_content" },
  { term: "sexting",        category: "sexual_content" },
  { term: "nudes",          category: "sexual_content" },
  { term: "nude",           category: "sexual_content" },
  { term: "naked",          category: "sexual_content" },
  { term: "clit",           category: "sexual_content" },
  { term: "clitoris",       category: "sexual_content" },
  { term: "vagina",         category: "sexual_content" },
  { term: "penis",          category: "sexual_content" },
  { term: "erection",       category: "sexual_content" },
  { term: "horny",          category: "sexual_content" },
  { term: "kinky",          category: "sexual_content" },
  { term: "fetish",         category: "sexual_content" },
  { term: "bdsm",           category: "sexual_content" },
  { term: "nsfw",           category: "sexual_content" },
  { term: "sexcam",         category: "sexual_content" },
  { term: "lust",           category: "sexual_content" },
  { term: "lusty",          category: "sexual_content" },
  { term: "perv",           category: "sexual_content" },
  { term: "pervert",        category: "sexual_content" },
  { term: "pedophile",      category: "sexual_content" },
  { term: "pedo",           category: "sexual_content" },
  { term: "paedophile",     category: "sexual_content" },
  { term: "incest",         category: "sexual_content" },
  { term: "bestiality",     category: "sexual_content" },

  // ── Slurs & identity-based hate ───────────────────────────────────────────
  { term: "nigger",         category: "slur" },
  { term: "nigga",          category: "slur" },
  { term: "nig",            category: "slur" },
  { term: "coon",           category: "slur" },
  { term: "jiggaboo",       category: "slur" },
  { term: "spook",          category: "slur" },
  { term: "sambo",          category: "slur" },
  { term: "faggot",         category: "slur" },
  { term: "fag",            category: "slur" },
  { term: "dyke",           category: "slur" },
  { term: "queer",          category: "slur" },  // used as slur in direct address
  { term: "kike",           category: "slur" },
  { term: "spic",           category: "slur" },
  { term: "chink",          category: "slur" },
  { term: "gook",           category: "slur" },
  { term: "jap",            category: "slur" },
  { term: "wetback",        category: "slur" },
  { term: "beaner",         category: "slur" },
  { term: "paki",           category: "slur" },
  { term: "raghead",        category: "slur" },
  { term: "towelhead",      category: "slur" },
  { term: "sandnigger",     category: "slur" },
  { term: "camel jockey",   category: "slur" },
  { term: "cracker",        category: "slur" },
  { term: "honky",          category: "slur" },
  { term: "tranny",         category: "slur" },
  { term: "shemale",        category: "slur" },
  { term: "retard",         category: "slur" },
  { term: "retarded",       category: "slur" },
  { term: "spaz",           category: "slur" },
  { term: "sped",           category: "slur" },
  { term: "tard",           category: "slur" },
  { term: "mongoloid",      category: "slur" },
  { term: "gyp",            category: "slur" },
  { term: "gypsy",          category: "slur" },
  { term: "gyppo",          category: "slur" },
  { term: "mick",           category: "slur" },
  { term: "kraut",          category: "slur" },
  { term: "nazi",           category: "slur" },
  { term: "feminazi",       category: "slur" },
  { term: "islamophobe",    category: "slur" },

  // ── Self-harm / threats (single word) ────────────────────────────────────
  { term: "kys",            category: "hate_speech" },
  { term: "kms",            category: "hate_speech" },
  { term: "kyl",            category: "hate_speech" },
  { term: "doxx",           category: "hate_speech" },
  { term: "dox",            category: "hate_speech" },
  { term: "swat",           category: "hate_speech" },  // as in swatting
  { term: "swatting",       category: "hate_speech" },
];

// ── Multi-word phrases (substring matched after normalisation) ─────────────────
// Listed in order of specificity — more specific phrases first.
export const PHRASE_TERMS: BannedEntry[] = [

  // ── Threats of violence / harm ────────────────────────────────────────────
  { term: "kill yourself",          category: "hate_speech" },
  { term: "kill ur self",           category: "hate_speech" },
  { term: "killyourself",           category: "hate_speech" },
  { term: "go kill yourself",       category: "hate_speech" },
  { term: "neck yourself",          category: "hate_speech" },
  { term: "hang yourself",          category: "hate_speech" },
  { term: "go die",                 category: "hate_speech" },
  { term: "i hope you die",         category: "hate_speech" },
  { term: "you should die",         category: "hate_speech" },
  { term: "drop dead",              category: "hate_speech" },
  { term: "i will kill you",        category: "hate_speech" },
  { term: "ill kill you",           category: "hate_speech" },
  { term: "im going to kill you",   category: "hate_speech" },
  { term: "gonna kill you",         category: "hate_speech" },
  { term: "i will find you",        category: "hate_speech" },
  { term: "i know where you live",  category: "hate_speech" },
  { term: "i know where u live",    category: "hate_speech" },
  { term: "i will hurt you",        category: "hate_speech" },
  { term: "i will rape",            category: "hate_speech" },
  { term: "ill rape",               category: "hate_speech" },
  { term: "gonna rape",             category: "hate_speech" },
  { term: "rape you",               category: "hate_speech" },
  { term: "rape ur",                category: "hate_speech" },
  { term: "i will dox",             category: "hate_speech" },
  { term: "ill dox you",            category: "hate_speech" },
  { term: "gonna swat",             category: "hate_speech" },

  // ── Sexual solicitation / harassment ──────────────────────────────────────
  { term: "send nudes",             category: "sexual_content" },
  { term: "send nude",              category: "sexual_content" },
  { term: "send me nudes",          category: "sexual_content" },
  { term: "send pics",              category: "sexual_content" },
  { term: "send me pics",           category: "sexual_content" },
  { term: "send me a pic",          category: "sexual_content" },
  { term: "show me your",           category: "sexual_content" },
  { term: "show ur",                category: "sexual_content" },
  { term: "want to fuck",           category: "sexual_content" },
  { term: "wanna fuck",             category: "sexual_content" },
  { term: "lets fuck",              category: "sexual_content" },
  { term: "let's fuck",             category: "sexual_content" },
  { term: "fuck me",                category: "sexual_content" },
  { term: "fuck you",               category: "sexual_content" },
  { term: "i want to fuck",         category: "sexual_content" },
  { term: "i wanna fuck",           category: "sexual_content" },
  { term: "wanna have sex",         category: "sexual_content" },
  { term: "want to have sex",       category: "sexual_content" },
  { term: "sleep with me",          category: "sexual_content" },
  { term: "have sex with me",       category: "sexual_content" },
  { term: "sex with me",            category: "sexual_content" },
  { term: "let me see you naked",   category: "sexual_content" },
  { term: "get naked for me",       category: "sexual_content" },
  { term: "sex tape",               category: "sexual_content" },
  { term: "make a sex tape",        category: "sexual_content" },
  { term: "naked pics",             category: "sexual_content" },
  { term: "naked photo",            category: "sexual_content" },
  { term: "nude photo",             category: "sexual_content" },
  { term: "you are sexy",           category: "sexual_content" },
  { term: "ur so sexy",             category: "sexual_content" },
  { term: "youre so hot",           category: "sexual_content" },
  { term: "i want your body",       category: "sexual_content" },
  { term: "i want to touch you",    category: "sexual_content" },
  { term: "touch yourself",         category: "sexual_content" },
  { term: "finger yourself",        category: "sexual_content" },
  { term: "suck my",                category: "sexual_content" },
  { term: "lick my",                category: "sexual_content" },
  { term: "blow me",                category: "sexual_content" },
  { term: "jerk me off",            category: "sexual_content" },
  { term: "jerk off",               category: "sexual_content" },

  // ── CSAM / child exploitation ─────────────────────────────────────────────
  { term: "child porn",             category: "sexual_content" },
  { term: "cp link",                category: "sexual_content" },
  { term: "kiddie porn",            category: "sexual_content" },
  { term: "loli",                   category: "sexual_content" },
  { term: "shota",                  category: "sexual_content" },
  { term: "jailbait",               category: "sexual_content" },
  { term: "underage",               category: "sexual_content" },
  { term: "minor nude",             category: "sexual_content" },

  // ── Compound profanity ────────────────────────────────────────────────────
  { term: "mother fucker",          category: "profanity" },
  { term: "son of a bitch",         category: "profanity" },
  { term: "son of bitch",           category: "profanity" },
  { term: "piece of shit",          category: "profanity" },
  { term: "you piece of",           category: "profanity" },
  { term: "you little shit",        category: "profanity" },
  { term: "dumb bitch",             category: "profanity" },
  { term: "dumb ass",               category: "profanity" },
  { term: "dumbass",                category: "profanity" },
  { term: "fat bitch",              category: "profanity" },
  { term: "fat ass",                category: "profanity" },
  { term: "shut up bitch",          category: "profanity" },
  { term: "stupid bitch",           category: "profanity" },
  { term: "ugly bitch",             category: "profanity" },

  // ── Hate speech phrases ────────────────────────────────────────────────────
  { term: "white power",            category: "hate_speech" },
  { term: "white supremacy",        category: "hate_speech" },
  { term: "heil hitler",            category: "hate_speech" },
  { term: "gas the",                category: "hate_speech" },
  { term: "ethnic cleansing",       category: "hate_speech" },
  { term: "go back to your country",category: "hate_speech" },
  { term: "go back to africa",      category: "hate_speech" },
  { term: "all muslims",            category: "hate_speech" },
  { term: "all jews",               category: "hate_speech" },
  { term: "islam is",               category: "hate_speech" },
  { term: "kill all",               category: "hate_speech" },

  // ── Obfuscated self-harm phrases ──────────────────────────────────────────
  { term: "killyurself",            category: "hate_speech" },
  { term: "killurself",             category: "hate_speech" },
  { term: "k1lly0urself",           category: "hate_speech" },
  { term: "kil ur self",            category: "hate_speech" },
];

// ── User-facing messages per category ─────────────────────────────────────────
export const CATEGORY_MESSAGES: Record<FilterCategory, string> = {
  profanity:
    "Your message contains language that violates our community guidelines and wasn't sent. Please keep conversations respectful.",
  sexual_content:
    "Your message contains sexually explicit or harassing content that violates our community guidelines and wasn't sent.",
  slur:
    "Your message contains a slur or hate speech that violates our community guidelines and wasn't sent. Vextorn is an inclusive, respectful space for everyone.",
  hate_speech:
    "Your message contains content that promotes harm or threatens others, which violates our community guidelines. It wasn't sent.",
};
